### PR TITLE
committing first code PR

### PR DESCRIPTION
**Pull request by zakariwilder**
Adding first new code

### CODE REVIEW

**Review by zakariwilder — COMMENTED** [review]
check this code is valid

**Review by zakariwilder — COMMENTED** [review]
check this code is valid

**Review by zakariwilder — COMMENTED** [review]
check this code is valid

**Comment by zakariwilder** [comment]
good

**Comment by Rwadxvv** [comment]
repo. chnger

**Comment by Rwadxvv** [comment]
>  @`[](tuyt) 

> #

`

**Comment by Rwadxvv** [comment]
IMG-20220729-WA0022

**Pull request closed without merging**
